from pathlib import Path

p=Path('netlify/functions/_restaurant-sot.ts')
s=p.read_text()
if "import { createHash } from 'node:crypto';" not in s:
    s=s.replace("import { decryptPii, piiHash } from './_operations-db';\n", "import { decryptPii, piiHash } from './_operations-db';\nimport { createHash } from 'node:crypto';\n", 1)
s=s.replace("  requestedFor: string; environment: string;\n};", "  requestedFor: string; environment: string; duplicate?: boolean;\n};", 1)
old='''export async function createRestaurantPreorder(input: {\n  guestDbId: string; channel: string; date: string; time: string;\n  items: Array<{ name: string; quantity: number }>;\n  customerName: string; phone?: string | null; email?: string | null; note?: string | null;\n}): Promise<PreorderCreateResult> {\n  const requestedFor = new Date(`${input.date}T${input.time}:00+07:00`);\n  if (Number.isNaN(requestedFor.valueOf())) throw new Error('invalid_requested_time');\n  const menu = await listRestaurantMenu();\n  const resolved = input.items.map(item => ({ menu: resolveMenuName(item.name, menu), quantity: Math.max(1, Math.min(50, Math.floor(item.quantity || 1))) }));\n  if (resolved.some(item => !item.menu)) throw new Error('menu_item_not_found');\n  for (const item of resolved) {\n    if (!item.menu!.is_orderable || item.menu!.available_servings < item.quantity) throw new Error(`menu_item_unavailable:${item.menu!.name}`);\n  }\n  const rid = await restaurantId();\n  const created = await rpc<{ id:string; preorderCode:string; totalAmount:number; status:string }>('create_restaurant_preorder', {\n    p_restaurant_id: rid, p_requested_for: requestedFor.toISOString(), p_customer_name: input.customerName,\n    p_phone: input.phone ?? '', p_email: input.email ?? '', p_source_channel: input.channel,\n    p_customer_note: input.note ?? '',\n    p_items: resolved.map(item => ({ menuItemId: item.menu!.menu_item_id, quantity: item.quantity })),\n  });\n  const environment = await guestEnvironment(input.guestDbId);\n  await chartDbFetch(`restaurant_preorders?id=eq.${created.id}`, {\n    method: 'PATCH', headers: { Prefer:'return=minimal' },\n    body: JSON.stringify({ guest_id: input.guestDbId, environment, updated_at: new Date().toISOString() }),\n  });\n  const result: PreorderCreateResult = {\n    ...created, items: resolved.map(item => ({ name:item.menu!.name, quantity:item.quantity })),\n    requestedFor: requestedFor.toISOString(), environment,\n  };\n  await notifyRestaurantPreorderTeam(created.id).catch(error => {\n    console.error('RESTAURANT_PREORDER_NOTIFY_ERROR', error instanceof Error ? error.message.slice(0,220) : 'unknown');\n  });\n  return result;\n}\n'''
new='''export async function createRestaurantPreorder(input: {\n  guestDbId: string; channel: string; date: string; time: string;\n  items: Array<{ name: string; quantity: number }>;\n  customerName: string; phone?: string | null; email?: string | null; note?: string | null;\n}): Promise<PreorderCreateResult> {\n  const requestedFor = new Date(`${input.date}T${input.time}:00+07:00`);\n  if (Number.isNaN(requestedFor.valueOf())) throw new Error('invalid_requested_time');\n  const menu = await listRestaurantMenu();\n  const resolved = input.items.map(item => ({ menu: resolveMenuName(item.name, menu), quantity: Math.max(1, Math.min(50, Math.floor(item.quantity || 1))) }));\n  if (resolved.some(item => !item.menu)) throw new Error('menu_item_not_found');\n  for (const item of resolved) {\n    if (!item.menu!.is_orderable || item.menu!.available_servings < item.quantity) throw new Error(`menu_item_unavailable:${item.menu!.name}`);\n  }\n  const environment = await guestEnvironment(input.guestDbId);\n  const canonicalItems = resolved\n    .map(item => ({ menuItemId:item.menu!.menu_item_id, quantity:item.quantity }))\n    .sort((a,b) => a.menuItemId.localeCompare(b.menuItemId));\n  const idempotencyKey = 'restaurant-preorder:v2:' + createHash('sha256').update(JSON.stringify({\n    guestDbId:input.guestDbId, requestedFor:requestedFor.toISOString(), items:canonicalItems,\n    customerName:input.customerName.trim().toLowerCase(), note:(input.note ?? '').trim(), environment,\n  })).digest('hex');\n  const rid = await restaurantId();\n  const created = await rpc<{ id:string; preorderCode:string; totalAmount:number; status:string; duplicate?:boolean }>('create_restaurant_preorder_v2', {\n    p_restaurant_id: rid, p_requested_for: requestedFor.toISOString(), p_customer_name: input.customerName,\n    p_phone: input.phone ?? '', p_email: input.email ?? '', p_source_channel: input.channel,\n    p_customer_note: input.note ?? '', p_items: canonicalItems, p_guest_id:input.guestDbId,\n    p_environment:environment, p_idempotency_key:idempotencyKey,\n  });\n  const result: PreorderCreateResult = {\n    ...created, items: resolved.map(item => ({ name:item.menu!.name, quantity:item.quantity })),\n    requestedFor: requestedFor.toISOString(), environment,\n  };\n  await notifyRestaurantPreorderTeam(created.id).catch(error => {\n    console.error('RESTAURANT_PREORDER_NOTIFY_ERROR', error instanceof Error ? error.message.slice(0,220) : 'unknown');\n  });\n  return result;\n}\n'''
if old not in s:
    raise SystemExit('createRestaurantPreorder block not found')
s=s.replace(old,new,1)
p.write_text(s)
