from pathlib import Path

p=Path('netlify/functions/thongthai-chat.ts')
s=p.read_text()

marker="""function mergeAfterTools(first: BrainResponse, second: BrainResponse): BrainResponse {\n  return {\n    ...first,\n    message: second.message,\n    responseStyle: second.responseStyle,\n    suggestedActions: second.suggestedActions.length ? second.suggestedActions : first.suggestedActions,\n    agentStateUpdate: mergeAgentState(first.agentStateUpdate, second.agentStateUpdate),\n    semanticMemoryUpdates: first.semanticMemoryUpdates,\n    toolCalls: [],\n  };\n}\n"""
insert=marker+"""\nfunction duplicateRestaurantPreorderMessage(\n  language: BrainRequest['language'],\n  toolResults: Array<{ name: string; ok: boolean; detail: string }>,\n): string | null {\n  const result = toolResults.find(item => item.name === 'create_restaurant_preorder' && item.ok);\n  if (!result) return null;\n  try {\n    const detail = JSON.parse(result.detail) as Record<string, unknown>;\n    if (detail.duplicate !== true || typeof detail.preorderCode !== 'string') return null;\n    const code = detail.preorderCode;\n    const messages: Record<BrainRequest['language'], string> = {\n      th: [\n        'รายการนี้มีอยู่แล้วครับ ✅',\n        'ทองไทยไม่ได้สร้างออเดอร์ซ้ำ',\n        `รหัสเดิม: ${code}`,\n        'สถานะ: รอร้านรับออเดอร์',\n        '',\n        'ระบบใช้คำขอเดิมของคุณครับ รอทีมร้านกดรับออเดอร์ได้เลย',\n      ].join('\\n'),\n      en: `This preorder already exists ✅\\nNo duplicate order was created.\\nExisting code: ${code}\\nStatus: waiting for the restaurant to accept.`,\n      zh: `这笔预订单已经存在 ✅\\n系统没有重复创建订单。\\n原订单号：${code}\\n状态：等待餐厅接单。`,\n      lo: `ລາຍການນີ້ມີຢູ່ແລ້ວ ✅\\nລະບົບບໍ່ໄດ້ສ້າງອໍເດີຊ້ຳ\\nລະຫັດເດີມ: ${code}\\nສະຖານະ: ລໍຖ້າຮ້ານຮັບອໍເດີ`,\n      vi: `Đơn đặt trước này đã tồn tại ✅\\nHệ thống không tạo đơn trùng.\\nMã cũ: ${code}\\nTrạng thái: đang chờ nhà hàng nhận đơn.`,\n    };\n    return messages[language];\n  } catch {\n    return null;\n  }\n}\n"""
if marker not in s: raise SystemExit('mergeAfterTools marker not found')
s=s.replace(marker,insert,1)

old="""    try {\n      const afterTools = await runThongthaiBrain(\n        request,\n        communityOfferings,\n        messages,\n        { ...runtime, toolResults },\n      );\n      finalResponse = mergeAfterTools(firstResponse, afterTools);\n    } catch (error) {\n      console.error('THONGTHAI_BRAIN_POST_TOOL_ERROR', error);\n      finalResponse = {\n        ...firstResponse,\n        toolCalls: [],\n        message: toolResults.every(result => result.ok)\n          ? firstResponse.message\n          : `${firstResponse.message}\\n\\nมีบางอย่างที่ทองไทยยังทำให้ไม่สำเร็จครับ ลองอีกครั้งได้เลย`,\n      };\n    }\n"""
new="""    const duplicatePreorderNotice = duplicateRestaurantPreorderMessage(request.language, toolResults);\n    if (duplicatePreorderNotice) {\n      // This is an idempotent replay of an existing preorder. Answer deterministically so\n      // the customer is never told a duplicate request was newly accepted.\n      finalResponse = {\n        ...firstResponse,\n        toolCalls: [],\n        suggestedActions: [],\n        message: duplicatePreorderNotice,\n      };\n    } else {\n      try {\n        const afterTools = await runThongthaiBrain(\n          request,\n          communityOfferings,\n          messages,\n          { ...runtime, toolResults },\n        );\n        finalResponse = mergeAfterTools(firstResponse, afterTools);\n      } catch (error) {\n        console.error('THONGTHAI_BRAIN_POST_TOOL_ERROR', error);\n        finalResponse = {\n          ...firstResponse,\n          toolCalls: [],\n          message: toolResults.every(result => result.ok)\n            ? firstResponse.message\n            : `${firstResponse.message}\\n\\nมีบางอย่างที่ทองไทยยังทำให้ไม่สำเร็จครับ ลองอีกครั้งได้เลย`,\n        };\n      }\n    }\n"""
if old not in s: raise SystemExit('post-tool marker not found')
s=s.replace(old,new,1)
p.write_text(s)

p=Path('netlify/functions/_thongthai-brain-v3.ts')
s=p.read_text()
old="""- Restaurant PREORDER is different from a restaurant/table booking. For food ordered ahead, collect exact menu items + quantity, pickup date, pickup time, customer name, and contact if the channel itself is not reachable. Then use create_restaurant_preorder. A successful preorder is REQUESTED until staff accepts it in the restaurant LINE group. Never claim staff accepted it before the tool result says so.\n"""
new=old+"""- If create_restaurant_preorder TOOL RESULT contains duplicate=true, this is an EXISTING preorder, not a new one. Explicitly say no duplicate was created, show the existing preorder code, and keep its existing status. Never say the duplicate request was newly accepted/recorded.\n"""
if old not in s: raise SystemExit('brain preorder marker not found')
s=s.replace(old,new,1)
p.write_text(s)
