-- THONGTHAI BRAIN V2 source-controlled migration
-- Production migration names: thongthai_brain_v2_identity_memory_world + thongthai_brain_v2_handoff_queue

create table if not exists public.guest_identities (
  id bigint generated by default as identity primary key,
  guest_id uuid not null references public.guests(id) on delete cascade,
  provider text not null check (provider in ('web','line','facebook','messenger','backoffice')),
  provider_user_key text not null check (char_length(provider_user_key) between 1 and 128),
  linked_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (provider, provider_user_key)
);

create index if not exists guest_identities_guest_idx on public.guest_identities(guest_id);

create table if not exists public.guest_agent_state (
  guest_id uuid primary key references public.guests(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  constraint guest_agent_state_object check (jsonb_typeof(state) = 'object')
);

create table if not exists public.guest_semantic_memory (
  id bigint generated by default as identity primary key,
  guest_id uuid not null references public.guests(id) on delete cascade,
  memory_key text not null check (memory_key ~ '^[a-z0-9_]{1,48}$'),
  memory_value jsonb not null,
  confidence numeric(4,3) not null default 0.700 check (confidence >= 0 and confidence <= 1),
  source_channel text not null check (source_channel in ('web','line','facebook','messenger','backoffice')),
  evidence_count integer not null default 1 check (evidence_count >= 1),
  status text not null default 'active' check (status in ('active','superseded')),
  first_observed_at timestamptz not null default now(),
  last_observed_at timestamptz not null default now(),
  unique (guest_id, memory_key)
);

create index if not exists guest_semantic_memory_guest_idx on public.guest_semantic_memory(guest_id, status, last_observed_at desc);

create table if not exists public.world_facts (
  fact_key text primary key check (fact_key ~ '^[a-z0-9_\.]{1,80}$'),
  category text not null,
  fact_value jsonb not null,
  verified boolean not null default false,
  active boolean not null default true,
  source text null,
  updated_at timestamptz not null default now()
);

create table if not exists public.handoff_requests (
  id uuid primary key default gen_random_uuid(),
  guest_id uuid not null references public.guests(id) on delete cascade,
  reason_code text not null check (reason_code in ('booking_help','accessibility_help','complaint','other')),
  source_channel text not null check (source_channel in ('web','line','facebook','messenger','backoffice')),
  status text not null default 'pending' check (status in ('pending','claimed','resolved','cancelled')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz null
);

create index if not exists handoff_requests_status_created_idx on public.handoff_requests(status, created_at desc);
create index if not exists handoff_requests_guest_created_idx on public.handoff_requests(guest_id, created_at desc);

insert into public.world_facts (fact_key, category, fact_value, verified, active, source)
values
  ('brand.name','brand','"ทำมา-ชาติ — Experiences of Isan"'::jsonb,true,true,'owner_verified'),
  ('brand.positioning','brand','"Isan Wellness Community"'::jsonb,true,true,'owner_verified'),
  ('location.google_maps','location','"https://maps.app.goo.gl/67eqn5vGvqJjfxZCA?g_st=ic"'::jsonb,true,true,'owner_verified'),
  ('ecosystem.inthanin','ecosystem','{"name":"Inthanin Café","role":"welcome_partner","first_physical_stop":true}'::jsonb,true,true,'owner_verified'),
  ('ecosystem.tamma_food','ecosystem','{"name":"ตำมา-ชาติ","role":"dining"}'::jsonb,true,true,'owner_verified'),
  ('ecosystem.homestay','ecosystem','{"name":"ทำมา-ชาติ เฮือนสเตย์","role":"stay"}'::jsonb,true,true,'owner_verified'),
  ('ecosystem.adventure','ecosystem','{"name":"ทำมา-ชาติ ผจญภัย","role":"outdoor_nature_adventure"}'::jsonb,true,true,'owner_verified')
on conflict (fact_key) do update set
  category = excluded.category,
  fact_value = excluded.fact_value,
  verified = excluded.verified,
  active = excluded.active,
  source = excluded.source,
  updated_at = now();

alter table public.guest_events drop constraint if exists guest_events_event_type_check;
alter table public.guest_events add constraint guest_events_event_type_check check (
  event_type in (
    'chat_request', 'information_request', 'journey_created',
    'journey_modified', 'journey_saved', 'journey_favorited', 'return_visit',
    'experience_favorited', 'experience_visited', 'identity_linked',
    'memory_learned', 'brain_decision', 'agent_action', 'handoff_requested'
  )
);

alter table public.guest_identities enable row level security;
alter table public.guest_agent_state enable row level security;
alter table public.guest_semantic_memory enable row level security;
alter table public.world_facts enable row level security;
alter table public.handoff_requests enable row level security;

revoke all on table public.guest_identities from anon, authenticated;
revoke all on table public.guest_agent_state from anon, authenticated;
revoke all on table public.guest_semantic_memory from anon, authenticated;
revoke all on table public.world_facts from anon, authenticated;
revoke all on table public.handoff_requests from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
