-- Thongthai Operations V1
-- Applied to production Supabase tamma-customer-data.
-- Customer PII lives only in encrypted *_enc columns; lookup hashes are one-way SHA-256.

create table if not exists public.customer_accounts (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique null references auth.users(id) on delete set null,
  guest_id uuid unique null references public.guests(id) on delete set null,
  full_name_enc text null,
  email_enc text null,
  email_hash text null,
  phone_enc text null,
  phone_hash text null,
  preferred_contact text null check (preferred_contact in ('line','phone','email')),
  service_contact_allowed boolean not null default true,
  marketing_opt_in boolean not null default false,
  test_label text null,
  is_test boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists customer_accounts_email_hash_uq on public.customer_accounts(email_hash) where email_hash is not null;
create unique index if not exists customer_accounts_phone_hash_uq on public.customer_accounts(phone_hash) where phone_hash is not null;

create table if not exists public.customer_channel_contacts (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.customer_accounts(id) on delete cascade,
  provider text not null check (provider in ('line','email','phone','facebook','messenger')),
  external_id_enc text not null,
  external_id_hash text not null,
  reachable boolean not null default true,
  verified boolean not null default false,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (provider, external_id_hash)
);
create index if not exists customer_channel_contacts_customer_idx on public.customer_channel_contacts(customer_id);

create table if not exists public.service_resources (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  service_type text not null check (service_type in ('restaurant','stay','activity','cafe')),
  name text not null,
  description text null,
  unit_label text null,
  default_capacity integer null check (default_capacity is null or default_capacity >= 0),
  requires_schedule boolean not null default true,
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_schedules (
  id uuid primary key default gen_random_uuid(),
  resource_id uuid not null references public.service_resources(id) on delete cascade,
  start_at timestamptz not null,
  end_at timestamptz not null,
  capacity_total integer not null check (capacity_total >= 0),
  capacity_reserved integer not null default 0 check (capacity_reserved >= 0),
  status text not null default 'open' check (status in ('open','closed','cancelled')),
  environment text not null default 'live' check (environment in ('live','test')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint service_schedules_time_order check (end_at > start_at),
  constraint service_schedules_reserved_lte_total check (capacity_reserved <= capacity_total),
  unique (resource_id, start_at, environment)
);
create index if not exists service_schedules_lookup_idx on public.service_schedules(resource_id, environment, start_at);

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  booking_code text unique not null default ('BK-' || to_char(now(),'YYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))),
  customer_id uuid null references public.customer_accounts(id) on delete set null,
  guest_id uuid null references public.guests(id) on delete set null,
  service_type text not null check (service_type in ('restaurant','stay','activity')),
  resource_id uuid not null references public.service_resources(id),
  start_at timestamptz not null,
  end_at timestamptz not null,
  party_size integer null check (party_size is null or party_size > 0),
  quantity integer not null default 1 check (quantity > 0),
  status text not null default 'requested' check (status in ('requested','confirmed','cancelled','completed','no_show')),
  source_channel text not null default 'web' check (source_channel in ('web','line','facebook','messenger','backoffice')),
  customer_note text null,
  booking_customer_name_enc text null,
  booking_phone_enc text null,
  booking_email_enc text null,
  staff_note text null,
  contact_status text not null default 'pending' check (contact_status in ('pending','contacted','replied','closed')),
  assigned_to text null,
  environment text not null default 'live' check (environment in ('live','test')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bookings_time_order check (end_at > start_at)
);
create index if not exists bookings_schedule_idx on public.bookings(environment,status,start_at);
create index if not exists bookings_customer_idx on public.bookings(customer_id,created_at desc);

create table if not exists public.booking_allocations (
  booking_id uuid not null references public.bookings(id) on delete cascade,
  schedule_id uuid not null references public.service_schedules(id) on delete restrict,
  capacity_units integer not null default 1 check (capacity_units > 0),
  primary key (booking_id,schedule_id)
);

create table if not exists public.cafe_inquiries (
  id uuid primary key default gen_random_uuid(),
  inquiry_code text unique not null default ('CF-' || to_char(now(),'YYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))),
  customer_id uuid null references public.customer_accounts(id) on delete set null,
  guest_id uuid null references public.guests(id) on delete set null,
  question text not null,
  status text not null default 'open' check (status in ('open','replied','closed')),
  source_channel text not null default 'web' check (source_channel in ('web','line','facebook','messenger','backoffice')),
  response_note text null,
  assigned_to text null,
  environment text not null default 'live' check (environment in ('live','test')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.otop_products (
  id uuid primary key default gen_random_uuid(),
  offering_id uuid null references public.community_offerings(offering_id) on delete set null,
  sku text unique not null,
  name text not null,
  description text null,
  price numeric(12,2) not null check (price >= 0),
  stock_qty integer not null default 0 check (stock_qty >= 0),
  active boolean not null default true,
  verified boolean not null default false,
  environment text not null default 'live' check (environment in ('live','test')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.otop_orders (
  id uuid primary key default gen_random_uuid(),
  order_code text unique not null default ('OR-' || to_char(now(),'YYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))),
  customer_id uuid null references public.customer_accounts(id) on delete set null,
  guest_id uuid null references public.guests(id) on delete set null,
  status text not null default 'requested' check (status in ('requested','confirmed','preparing','ready','shipped','completed','cancelled')),
  source_channel text not null default 'web' check (source_channel in ('web','line','facebook','messenger','backoffice')),
  fulfillment_type text not null default 'pickup' check (fulfillment_type in ('pickup','shipping')),
  shipping_address_enc text null,
  customer_note text null,
  staff_note text null,
  total_amount numeric(12,2) not null default 0 check (total_amount >= 0),
  contact_status text not null default 'pending' check (contact_status in ('pending','contacted','replied','closed')),
  environment text not null default 'live' check (environment in ('live','test')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.otop_order_items (
  order_id uuid not null references public.otop_orders(id) on delete cascade,
  product_id uuid not null references public.otop_products(id),
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  line_total numeric(12,2) generated always as (quantity * unit_price) stored,
  primary key (order_id,product_id)
);

create table if not exists public.customer_contact_logs (
  id bigint generated by default as identity primary key,
  customer_id uuid null references public.customer_accounts(id) on delete set null,
  booking_id uuid null references public.bookings(id) on delete set null,
  order_id uuid null references public.otop_orders(id) on delete set null,
  inquiry_id uuid null references public.cafe_inquiries(id) on delete set null,
  channel text not null check (channel in ('line','phone','email','other')),
  direction text not null default 'outbound' check (direction in ('outbound','inbound')),
  status text not null default 'attempted' check (status in ('attempted','sent','connected','failed','replied')),
  note text null,
  created_by text null,
  created_at timestamptz not null default now()
);

create table if not exists public.backoffice_activity (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('booking','order','inquiry','customer','schedule','product')),
  entity_id text not null,
  action text not null,
  actor text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Capacity is reserved atomically by booking_allocations triggers in production.
-- OTOP stock is locked/decremented atomically by otop_order_items triggers and restored on cancellation.
-- Customer account rows are auto-created when Supabase Auth users sign up.
-- All operational tables have RLS enabled and anon/authenticated direct access revoked; server-side service-role access only.
