-- ทำมา-ชาติ Customer Memory Database
-- Structured travel memory only. Raw chat text and personal identifiers are prohibited.

create extension if not exists pgcrypto;

create table if not exists public.guests (
  id uuid primary key default gen_random_uuid(),
  anonymous_id uuid unique not null,
  language text null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.guest_memory (
  guest_id uuid not null references public.guests(id) on delete cascade,
  memory_key text not null,
  memory_value jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (guest_id, memory_key),
  constraint guest_memory_key_allowed check (
    memory_key in (
      'traveler_type', 'trip_duration', 'group', 'interests', 'pace',
      'budget_band', 'constraints', 'visited_experiences', 'favorites',
      'preferred_language'
    )
  ),
  constraint guest_memory_value_allowed check (
    case memory_key
      when 'traveler_type' then memory_value in (
        '"solo"'::jsonb, '"couple"'::jsonb, '"friends"'::jsonb,
        '"family"'::jsonb, '"group"'::jsonb
      )
      when 'trip_duration' then memory_value in (
        '"short"'::jsonb, '"half"'::jsonb, '"full"'::jsonb,
        '"overnight"'::jsonb, '"2d1n"'::jsonb, '"3d2n"'::jsonb
      )
      when 'pace' then memory_value in (
        '"slow"'::jsonb, '"relaxed"'::jsonb, '"balanced"'::jsonb, '"active"'::jsonb
      )
      when 'budget_band' then memory_value in (
        '"under_3000"'::jsonb, '"3000_8000"'::jsonb,
        '"8000_15000"'::jsonb, '"15000_plus"'::jsonb
      )
      when 'preferred_language' then memory_value in (
        '"th"'::jsonb, '"en"'::jsonb, '"zh"'::jsonb, '"lo"'::jsonb, '"vi"'::jsonb
      )
      when 'interests' then
        jsonb_typeof(memory_value) = 'array'
        and memory_value <@ '["food","nature","adventure","rest","culture","coffee","local_community","family","photography","wellness"]'::jsonb
      when 'constraints' then
        jsonb_typeof(memory_value) = 'array'
        and memory_value <@ '["limited_walking","wheelchair_access","elderly_friendly","child_friendly","vegetarian","no_spicy","rain_sensitive"]'::jsonb
      when 'group' then
        jsonb_typeof(memory_value) = 'object'
        and memory_value - 'adults' - 'children' - 'elderly' = '{}'::jsonb
      when 'visited_experiences' then jsonb_typeof(memory_value) = 'array'
      when 'favorites' then jsonb_typeof(memory_value) = 'array'
      else false
    end
  )
);

create table if not exists public.journeys (
  id uuid primary key default gen_random_uuid(),
  guest_id uuid not null references public.guests(id) on delete cascade,
  action text not null check (action in ('create', 'modify', 'replace', 'save')),
  intent text null,
  journey jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.guest_events (
  id bigint generated by default as identity primary key,
  guest_id uuid null references public.guests(id) on delete cascade,
  event_type text not null check (
    event_type in (
      'chat_request', 'information_request', 'journey_created',
      'journey_modified', 'journey_saved', 'journey_favorited', 'return_visit'
    )
  ),
  intent text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint guest_events_no_chat_text check (
    not (metadata ?| array['message', 'chat', 'chat_text', 'text', 'transcript', 'prompt'])
  )
);

create index if not exists guests_last_seen_at_idx on public.guests(last_seen_at desc);
create index if not exists journeys_guest_created_idx on public.journeys(guest_id, created_at desc);
create index if not exists guest_events_guest_created_idx on public.guest_events(guest_id, created_at desc);
create index if not exists guest_events_type_created_idx on public.guest_events(event_type, created_at desc);

alter table public.guests enable row level security;
alter table public.guest_memory enable row level security;
alter table public.journeys enable row level security;
alter table public.guest_events enable row level security;

-- Deliberately no policies for anon or authenticated roles.
-- Only the server-side Supabase secret/service credential may access these tables.
revoke all on table public.guests from anon, authenticated;
revoke all on table public.guest_memory from anon, authenticated;
revoke all on table public.journeys from anon, authenticated;
revoke all on table public.guest_events from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
