-- ทำมา-ชาติ Customer Memory Database
-- Structured travel memory only. Raw chat text and personal identifiers are prohibited.

create extension if not exists pgcrypto;

create table if not exists public.guests (
  id uuid primary key default gen_random_uuid(),
  anonymous_id uuid unique not null,
  language text null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.guest_memory (
  guest_id uuid not null references public.guests(id) on delete cascade,
  memory_key text not null,
  memory_value jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (guest_id, memory_key),
  constraint guest_memory_key_allowed check (
    memory_key in (
      'traveler_type', 'trip_duration', 'group', 'interests', 'pace',
      'budget_band', 'constraints', 'visited_experiences', 'favorites',
      'preferred_language'
    )
  ),
  constraint guest_memory_value_allowed check (
    case memory_key
      when 'traveler_type' then memory_value in (
        '"solo"'::jsonb, '"couple"'::jsonb, '"friends"'::jsonb,
        '"family"'::jsonb, '"group"'::jsonb
      )
      when 'trip_duration' then memory_value in (
        '"short"'::jsonb, '"half"'::jsonb, '"full"'::jsonb,
        '"overnight"'::jsonb, '"2d1n"'::jsonb, '"3d2n"'::jsonb
      )
      when 'pace' then memory_value in (
        '"slow"'::jsonb, '"relaxed"'::jsonb, '"balanced"'::jsonb, '"active"'::jsonb
      )
      when 'budget_band' then memory_value in (
        '"under_3000"'::jsonb, '"3000_8000"'::jsonb,
        '"8000_15000"'::jsonb, '"15000_plus"'::jsonb
      )
      when 'preferred_language' then memory_value in (
        '"th"'::jsonb, '"en"'::jsonb, '"zh"'::jsonb, '"lo"'::jsonb, '"vi"'::jsonb
      )
      when 'interests' then
        jsonb_typeof(memory_value) = 'array'
        and memory_value <@ '["food","nature","adventure","rest","culture","coffee","local_community","family","photography","wellness"]'::jsonb
      when 'constraints' then
        jsonb_typeof(memory_value) = 'array'
        and memory_value <@ '["limited_walking","wheelchair_access","elderly_friendly","child_friendly","vegetarian","no_spicy","rain_sensitive"]'::jsonb
      when 'group' then
        jsonb_typeof(memory_value) = 'object'
        and memory_value - 'adults' - 'children' - 'elderly' = '{}'::jsonb
      when 'visited_experiences' then jsonb_typeof(memory_value) = 'array'
      when 'favorites' then jsonb_typeof(memory_value) = 'array'
      else false
    end
  )
);

create table if not exists public.journeys (
  id uuid primary key default gen_random_uuid(),
  guest_id uuid not null references public.guests(id) on delete cascade,
  action text not null check (action in ('create', 'modify', 'replace', 'save')),
  intent text null,
  journey jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.guest_events (
  id bigint generated by default as identity primary key,
  guest_id uuid null references public.guests(id) on delete cascade,
  event_type text not null,
  intent text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- The constraints below are declared via explicit ALTER (drop + add) rather
-- than inline on CREATE TABLE. `create table if not exists` is a no-op once
-- a table already exists, so an inline constraint clause here would never
-- reach an already-deployed table when this file gains a new constraint or
-- a new allowed value later. ALTER makes re-running this file self-healing:
-- it always converges the live schema to match this file, on a fresh
-- database or an existing one.
-- ---------------------------------------------------------------------------
alter table public.guest_events drop constraint if exists guest_events_event_type_check;
alter table public.guest_events add constraint guest_events_event_type_check check (
  event_type in (
    'chat_request', 'information_request', 'journey_created',
    'journey_modified', 'journey_saved', 'journey_favorited', 'return_visit',
    'experience_favorited', 'experience_visited'
  )
);

alter table public.guest_events drop constraint if exists guest_events_no_chat_text;
alter table public.guest_events add constraint guest_events_no_chat_text check (
  not (metadata ?| array['message', 'chat', 'chat_text', 'text', 'transcript', 'prompt'])
);

alter table public.guest_memory drop constraint if exists guest_memory_value_allowed;
alter table public.guest_memory add constraint guest_memory_value_allowed check (
  case memory_key
    when 'traveler_type' then memory_value in (
      '"solo"'::jsonb, '"couple"'::jsonb, '"friends"'::jsonb,
      '"family"'::jsonb, '"group"'::jsonb
    )
    when 'trip_duration' then memory_value in (
      '"short"'::jsonb, '"half"'::jsonb, '"full"'::jsonb,
      '"overnight"'::jsonb, '"2d1n"'::jsonb, '"3d2n"'::jsonb
    )
    when 'pace' then memory_value in (
      '"slow"'::jsonb, '"relaxed"'::jsonb, '"balanced"'::jsonb, '"active"'::jsonb
    )
    when 'budget_band' then memory_value in (
      '"under_3000"'::jsonb, '"3000_8000"'::jsonb,
      '"8000_15000"'::jsonb, '"15000_plus"'::jsonb
    )
    when 'preferred_language' then memory_value in (
      '"th"'::jsonb, '"en"'::jsonb, '"zh"'::jsonb, '"lo"'::jsonb, '"vi"'::jsonb
    )
    when 'interests' then
      jsonb_typeof(memory_value) = 'array'
      and memory_value <@ '["food","nature","adventure","rest","culture","coffee","local_community","family","photography","wellness"]'::jsonb
    when 'constraints' then
      jsonb_typeof(memory_value) = 'array'
      and memory_value <@ '["limited_walking","wheelchair_access","elderly_friendly","child_friendly","vegetarian","no_spicy","rain_sensitive"]'::jsonb
    when 'group' then
      jsonb_typeof(memory_value) = 'object'
      and memory_value - 'adults' - 'children' - 'elderly' = '{}'::jsonb
    when 'visited_experiences' then jsonb_typeof(memory_value) = 'array'
    when 'favorites' then jsonb_typeof(memory_value) = 'array'
    else false
  end
);

-- ---------------------------------------------------------------------------
-- Community / OTOP foundation — real local partners and their offerings.
-- No customer data lives here; this is catalog data curated by the business,
-- read-only from the customer-facing product. loadVerifiedCommunityOfferings()
-- in _customer-db.ts only ever selects rows with active=true and
-- verified=true — nothing here is customer PII, and nothing is shown to a
-- guest (or mentioned by Thongthai) until verified.
-- ---------------------------------------------------------------------------
create table if not exists public.community_partners (
  partner_id uuid primary key default gen_random_uuid(),
  partner_name text not null,
  partner_type text null,
  community_name text null,
  district text null,
  province text null,
  verified boolean not null default false,
  active boolean not null default true,
  source_url text null,
  verified_at timestamptz null,
  created_at timestamptz not null default now()
);

create table if not exists public.community_offerings (
  offering_id uuid primary key default gen_random_uuid(),
  partner_id uuid not null references public.community_partners(partner_id) on delete cascade,
  offering_name text not null,
  offering_type text not null check (
    offering_type in (
      'product', 'food', 'workshop', 'cultural_experience',
      'wellness', 'agriculture', 'craft', 'activity'
    )
  ),
  description text null,
  tags jsonb not null default '[]'::jsonb,
  suitable_for jsonb not null default '[]'::jsonb,
  duration_minutes integer null,
  price_min numeric null,
  price_max numeric null,
  booking_required boolean not null default false,
  location_text text null,
  external_url text null,
  verified boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint community_offerings_price_order check (
    price_min is null or price_max is null or price_min <= price_max
  ),
  constraint community_offerings_tags_array check (jsonb_typeof(tags) = 'array'),
  constraint community_offerings_suitable_for_array check (jsonb_typeof(suitable_for) = 'array')
);

create index if not exists guests_last_seen_at_idx on public.guests(last_seen_at desc);
create index if not exists journeys_guest_created_idx on public.journeys(guest_id, created_at desc);
create index if not exists guest_events_guest_created_idx on public.guest_events(guest_id, created_at desc);
create index if not exists guest_events_type_created_idx on public.guest_events(event_type, created_at desc);
create index if not exists community_offerings_partner_idx on public.community_offerings(partner_id);
create index if not exists community_offerings_visible_idx on public.community_offerings(active, verified);

alter table public.guests enable row level security;
alter table public.guest_memory enable row level security;
alter table public.journeys enable row level security;
alter table public.guest_events enable row level security;
alter table public.community_partners enable row level security;
alter table public.community_offerings enable row level security;

-- Deliberately no policies for anon or authenticated roles.
-- Only the server-side Supabase secret/service credential may access these tables.
revoke all on table public.guests from anon, authenticated;
revoke all on table public.guest_memory from anon, authenticated;
revoke all on table public.journeys from anon, authenticated;
revoke all on table public.guest_events from anon, authenticated;
revoke all on table public.community_partners from anon, authenticated;
revoke all on table public.community_offerings from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
