-- Faithful reduction of the EXISTING snk-life-os-private schema (project pbbihfipfbpiqbiqlagd) for the tables
-- the SNK MONEY migration extends.  Captured from information_schema / pg_constraint / pg_policies / pg_indexes;
-- only unrelated tables (projects, businesses, ...) are stubbed so the real foreign keys can exist.
create schema if not exists auth;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true),'')::uuid $$;

create function public.snk_touch_updated_at() returns trigger language plpgsql set search_path to '' as $$
begin new.updated_at = now(); return new; end; $$;

create table public.businesses(id uuid primary key default gen_random_uuid());
create table public.projects(id uuid primary key default gen_random_uuid());

create table public.financial_accounts(
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  account_type text not null default 'bank',
  institution text,
  currency text not null default 'THB',
  opening_balance numeric not null default 0,
  is_active boolean not null default true,
  notes text,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.transaction_categories(
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  transaction_type text not null default 'expense',
  color text, icon text,
  position integer not null default 0,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(owner_id,name,transaction_type)
);
create table public.transactions(
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  business_id uuid references public.businesses(id) on delete set null,
  project_id uuid references public.projects(id) on delete set null,
  type text not null,
  amount numeric not null,
  currency text not null default 'THB',
  category text,
  description text,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  account_id uuid references public.financial_accounts(id) on delete set null,
  transfer_account_id uuid references public.financial_accounts(id) on delete set null,
  category_id uuid references public.transaction_categories(id) on delete set null,
  merchant text,
  notes text,
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  constraint transactions_type_check check (type = any (array['income','expense']))
);
create index transactions_owner_occurred_idx on public.transactions(owner_id, occurred_at desc);
create table public.recurring_transactions(
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null,
  type text not null,
  amount numeric not null,
  currency text not null default 'THB',
  frequency text not null,
  next_occurrence date,
  business_id uuid references public.businesses(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  project_id uuid references public.projects(id) on delete set null,
  due_day smallint,
  notes text,
  is_active boolean not null default true,
  archived_at timestamptz,
  account_id uuid references public.financial_accounts(id) on delete set null,
  category_id uuid references public.transaction_categories(id) on delete set null,
  constraint recurring_transactions_frequency_check check (frequency = any (array['daily','weekly','monthly','yearly'])),
  constraint recurring_transactions_type_check check (type = any (array['income','expense']))
);
create table public.activity_log(
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  entity_type text not null,
  entity_id uuid,
  action text not null,
  description text,
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);
create index activity_log_owner_created_idx on public.activity_log(owner_id, created_at desc);
create table public.user_settings(
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  key text not null,
  value jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(owner_id,key)
);
do $$ declare t text; begin
  foreach t in array array['financial_accounts','transaction_categories','transactions','recurring_transactions','activity_log','user_settings'] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('create policy %I on public.%I for all using (owner_id = auth.uid()) with check (owner_id = auth.uid())',t||'_owner',t);
  end loop;
  foreach t in array array['financial_accounts','transaction_categories','transactions','recurring_transactions'] loop
    execute format('create trigger snk_touch_updated_at before update on public.%I for each row execute function public.snk_touch_updated_at()',t);
  end loop;
end $$;
-- Supabase default privileges
grant all on all tables in schema public to anon, authenticated, service_role;
