-- Member delivery v1: encrypted reusable addresses, atomic multi-item OTOP
-- checkout, shipping totals, tracking and customer-visible status history.

create table if not exists public.customer_addresses (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customer_accounts(id) on delete cascade,
  label text not null check (char_length(label) between 1 and 60),
  recipient_name_enc text not null,
  phone_enc text not null,
  address_line1_enc text not null,
  address_line2_enc text null,
  subdistrict_enc text null,
  district_enc text not null,
  province text not null check (char_length(province) between 1 and 80),
  postal_code_enc text not null,
  delivery_instructions_enc text null,
  is_default boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists customer_addresses_customer_idx
  on public.customer_addresses(customer_id, active, created_at desc);
create unique index if not exists customer_addresses_one_default_uq
  on public.customer_addresses(customer_id) where is_default and active;

alter table public.customer_addresses enable row level security;
revoke all on table public.customer_addresses from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.customer_addresses to service_role;

create table if not exists public.otop_shipping_settings (
  id text primary key default 'default' check (id = 'default'),
  enabled boolean not null default true,
  domestic_base_fee numeric(12,2) not null default 60 check (domestic_base_fee >= 0),
  free_shipping_threshold numeric(12,2) null check (free_shipping_threshold is null or free_shipping_threshold >= 0),
  estimated_min_days integer not null default 2 check (estimated_min_days between 1 and 30),
  estimated_max_days integer not null default 5 check (estimated_max_days between estimated_min_days and 60),
  updated_at timestamptz not null default now()
);

insert into public.otop_shipping_settings (
  id, enabled, domestic_base_fee, free_shipping_threshold, estimated_min_days, estimated_max_days
) values ('default', true, 60, 1500, 2, 5)
on conflict (id) do nothing;

alter table public.otop_shipping_settings enable row level security;
revoke all on table public.otop_shipping_settings from public, anon, authenticated, service_role;
grant select, update on table public.otop_shipping_settings to service_role;

alter table public.otop_orders
  add column if not exists checkout_idempotency_key text null,
  add column if not exists shipping_address_id uuid null references public.customer_addresses(id) on delete set null,
  add column if not exists shipping_recipient_name_enc text null,
  add column if not exists shipping_phone_enc text null,
  add column if not exists subtotal_amount numeric(12,2) not null default 0 check (subtotal_amount >= 0),
  add column if not exists shipping_fee numeric(12,2) not null default 0 check (shipping_fee >= 0),
  add column if not exists shipping_status text null,
  add column if not exists carrier_name text null,
  add column if not exists tracking_number_enc text null,
  add column if not exists tracking_url text null,
  add column if not exists shipped_at timestamptz null,
  add column if not exists delivered_at timestamptz null;

alter table public.otop_orders
  drop constraint if exists otop_orders_shipping_status_check;
alter table public.otop_orders
  add constraint otop_orders_shipping_status_check check (
    shipping_status is null or shipping_status in (
      'awaiting_payment','packing','ready_to_ship','shipped',
      'delivered','delivery_failed','returned','cancelled'
    )
  );

create unique index if not exists otop_orders_checkout_idempotency_uq
  on public.otop_orders(customer_id, checkout_idempotency_key)
  where checkout_idempotency_key is not null;
create index if not exists otop_orders_shipping_queue_idx
  on public.otop_orders(environment, shipping_status, created_at desc)
  where fulfillment_type = 'shipping';

create table if not exists public.otop_shipping_events (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.otop_orders(id) on delete cascade,
  status text not null check (status in (
    'awaiting_payment','packing','ready_to_ship','shipped',
    'delivered','delivery_failed','returned','cancelled'
  )),
  customer_message text null check (customer_message is null or char_length(customer_message) <= 500),
  actor text null check (actor is null or char_length(actor) <= 120),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists otop_shipping_events_order_idx
  on public.otop_shipping_events(order_id, created_at asc);
alter table public.otop_shipping_events enable row level security;
revoke all on table public.otop_shipping_events from public, anon, authenticated, service_role;
revoke all on sequence public.otop_shipping_events_id_seq from public, anon, authenticated, service_role;
grant select, insert on table public.otop_shipping_events to service_role;
grant usage, select on sequence public.otop_shipping_events_id_seq to service_role;

create or replace function public.otop_shipping_status_guard()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.fulfillment_type <> 'shipping' then
    new.shipping_status := null;
    return new;
  end if;

  if not (
    (old.shipping_status = 'awaiting_payment' and new.shipping_status in ('packing','cancelled'))
    or (old.shipping_status = 'packing' and new.shipping_status in ('ready_to_ship','cancelled'))
    or (old.shipping_status = 'ready_to_ship' and new.shipping_status in ('shipped','cancelled'))
    or (old.shipping_status = 'shipped' and new.shipping_status in ('delivered','delivery_failed','returned'))
    or (old.shipping_status = 'delivery_failed' and new.shipping_status in ('shipped','returned','cancelled'))
    or (old.shipping_status = 'returned' and new.shipping_status = 'cancelled')
  ) then
    raise exception 'invalid_shipping_transition:%->%', old.shipping_status, new.shipping_status;
  end if;

  if new.shipping_status = 'packing' then
    new.status := case when new.status = 'requested' then 'confirmed' else new.status end;
  elsif new.shipping_status = 'ready_to_ship' then
    new.status := case when new.status in ('requested','confirmed') then 'preparing' else new.status end;
  elsif new.shipping_status = 'shipped' then
    new.status := 'shipped';
    new.shipped_at := coalesce(new.shipped_at, now());
  elsif new.shipping_status = 'delivered' then
    new.status := 'completed';
    new.delivered_at := coalesce(new.delivered_at, now());
  elsif new.shipping_status = 'cancelled' then
    new.status := 'cancelled';
  end if;
  new.updated_at := now();
  return new;
end;
$$;

revoke all on function public.otop_shipping_status_guard() from public, anon, authenticated;
grant execute on function public.otop_shipping_status_guard() to service_role;

drop trigger if exists otop_shipping_status_guard on public.otop_orders;
create trigger otop_shipping_status_guard
before update of shipping_status on public.otop_orders
for each row
when (old.shipping_status is distinct from new.shipping_status)
execute function public.otop_shipping_status_guard();

create or replace function public.record_otop_shipping_status_event()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_message text;
begin
  v_message := case new.shipping_status
    when 'packing' then 'รับชำระแล้ว กำลังเตรียมสินค้า'
    when 'ready_to_ship' then 'เตรียมสินค้าเรียบร้อย รอส่งมอบให้ขนส่ง'
    when 'shipped' then 'ส่งสินค้าให้บริษัทขนส่งแล้ว'
    when 'delivered' then 'จัดส่งสำเร็จแล้ว'
    when 'delivery_failed' then 'บริษัทขนส่งยังนำจ่ายไม่สำเร็จ ทีมงานกำลังติดตาม'
    when 'returned' then 'พัสดุถูกตีกลับ ทีมงานจะติดต่อเพื่อดำเนินการต่อ'
    when 'cancelled' then 'ยกเลิกการจัดส่งแล้ว'
    else 'อัปเดตสถานะการจัดส่งแล้ว'
  end;
  insert into public.otop_shipping_events(order_id, status, customer_message, actor)
  values (new.id, new.shipping_status, v_message, 'system');
  return new;
end;
$$;

revoke all on function public.record_otop_shipping_status_event() from public, anon, authenticated;
grant execute on function public.record_otop_shipping_status_event() to service_role;

drop trigger if exists record_otop_shipping_status_event on public.otop_orders;
create trigger record_otop_shipping_status_event
after update of shipping_status on public.otop_orders
for each row
when (old.shipping_status is distinct from new.shipping_status and new.shipping_status is not null)
execute function public.record_otop_shipping_status_event();

create or replace function public.sync_otop_shipping_after_payment()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.entity_type = 'otop_order'
     and old.status is distinct from new.status
     and new.status = 'verified' then
    update public.otop_orders
    set shipping_status = 'packing'
    where id = new.entity_id
      and fulfillment_type = 'shipping'
      and shipping_status = 'awaiting_payment';
  elsif new.entity_type = 'otop_order'
     and old.status is distinct from new.status
     and new.status = 'cancelled' then
    update public.otop_orders
    set shipping_status = 'cancelled'
    where id = new.entity_id
      and fulfillment_type = 'shipping'
      and shipping_status is distinct from 'cancelled';
  end if;
  return new;
end;
$$;

revoke all on function public.sync_otop_shipping_after_payment() from public, anon, authenticated;
grant execute on function public.sync_otop_shipping_after_payment() to service_role;

drop trigger if exists sync_otop_shipping_after_payment on public.payment_requests;
create trigger sync_otop_shipping_after_payment
after update of status on public.payment_requests
for each row execute function public.sync_otop_shipping_after_payment();

create or replace function public.create_member_otop_order_v1(
  p_customer_id uuid,
  p_guest_id uuid,
  p_items jsonb,
  p_shipping_address_id uuid,
  p_shipping_recipient_name_enc text,
  p_shipping_phone_enc text,
  p_shipping_address_enc text,
  p_customer_note text,
  p_shipping_fee numeric,
  p_checkout_idempotency_key text,
  p_environment text default 'live'
)
returns table (
  order_id uuid,
  order_code text,
  subtotal numeric,
  shipping_fee numeric,
  total numeric,
  payment_code text,
  shipping_status text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order public.otop_orders%rowtype;
  v_product record;
  v_item record;
  v_subtotal numeric(12,2) := 0;
  v_fee numeric(12,2) := 0;
  v_shipping public.otop_shipping_settings%rowtype;
  v_line_items jsonb := '[]'::jsonb;
  v_payment_code text;
begin
  if p_environment not in ('live','test') then raise exception 'invalid_environment'; end if;
  if p_checkout_idempotency_key is null or char_length(p_checkout_idempotency_key) < 16 then
    raise exception 'idempotency_key_required';
  end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) < 1 or jsonb_array_length(p_items) > 30 then
    raise exception 'invalid_items';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(p_items) elem
    where jsonb_typeof(elem) <> 'object'
       or not (elem ? 'sku' and elem ? 'quantity')
       or jsonb_typeof(elem->'sku') <> 'string'
       or jsonb_typeof(elem->'quantity') <> 'number'
       or (elem->>'sku') !~ '^[A-Z0-9][A-Z0-9_-]{2,79}$'
       or (elem->>'quantity') !~ '^[0-9]{1,2}$'
  ) then
    raise exception 'invalid_items';
  end if;
  if not exists (select 1 from public.customer_accounts c where c.id = p_customer_id and c.member_status = 'member') then
    raise exception 'member_required';
  end if;
  if not exists (
    select 1 from public.customer_addresses a
    where a.id = p_shipping_address_id and a.customer_id = p_customer_id and a.active
  ) then
    raise exception 'shipping_address_not_found';
  end if;

  select o.* into v_order
  from public.otop_orders o
  where o.customer_id = p_customer_id
    and o.checkout_idempotency_key = p_checkout_idempotency_key
  limit 1;

  if found then
    select pr.payment_code into v_payment_code
    from public.payment_requests pr
    where pr.entity_type = 'otop_order' and pr.entity_id = v_order.id
    limit 1;
    return query select v_order.id, v_order.order_code, v_order.subtotal_amount,
      v_order.shipping_fee, v_order.total_amount, v_payment_code, v_order.shipping_status;
    return;
  end if;

  for v_item in
    select elem->>'sku' as sku, sum((elem->>'quantity')::integer)::integer as quantity
    from jsonb_array_elements(p_items) elem
    group by elem->>'sku'
  loop
    if v_item.quantity < 1 or v_item.quantity > 99 then raise exception 'invalid_quantity'; end if;
    select p.id, p.sku, p.price, p.stock_qty into v_product
    from public.otop_products p
    where p.sku = v_item.sku
      and p.environment = p_environment
      and p.active and p.verified
    for update;
    if not found then raise exception 'product_not_available:%', v_item.sku; end if;
    if v_product.stock_qty < v_item.quantity then raise exception 'insufficient_stock:%', v_item.sku; end if;
    v_subtotal := v_subtotal + (v_product.price * v_item.quantity);
    v_line_items := v_line_items || jsonb_build_array(jsonb_build_object(
      'product_id', v_product.id,
      'quantity', v_item.quantity,
      'unit_price', v_product.price
    ));
  end loop;

  if jsonb_array_length(v_line_items) < 1 then raise exception 'invalid_items'; end if;

  select * into v_shipping
  from public.otop_shipping_settings s
  where s.id = 'default'
  for share;
  if not found or not v_shipping.enabled then raise exception 'shipping_temporarily_unavailable'; end if;
  v_fee := case
    when v_shipping.free_shipping_threshold is not null
      and v_subtotal >= v_shipping.free_shipping_threshold then 0
    else v_shipping.domestic_base_fee
  end;
  if p_shipping_fee is null or abs(p_shipping_fee - v_fee) > 0.001 then
    raise exception 'shipping_quote_changed';
  end if;

  insert into public.otop_orders (
    customer_id, guest_id, source_channel, fulfillment_type,
    shipping_address_id, shipping_recipient_name_enc, shipping_phone_enc,
    shipping_address_enc, customer_note, subtotal_amount, shipping_fee,
    total_amount, shipping_status, checkout_idempotency_key, environment
  ) values (
    p_customer_id, p_guest_id, 'web', 'shipping',
    p_shipping_address_id, p_shipping_recipient_name_enc, p_shipping_phone_enc,
    p_shipping_address_enc, left(p_customer_note, 1000), v_subtotal, v_fee,
    v_subtotal + v_fee, 'awaiting_payment', p_checkout_idempotency_key, p_environment
  ) returning * into v_order;

  insert into public.otop_order_items(order_id, product_id, quantity, unit_price)
  select v_order.id,
         (item->>'product_id')::uuid,
         (item->>'quantity')::integer,
         (item->>'unit_price')::numeric
  from jsonb_array_elements(v_line_items) item;

  insert into public.otop_shipping_events(order_id, status, customer_message, actor)
  values (v_order.id, 'awaiting_payment', 'รับคำสั่งซื้อแล้ว รอตรวจสอบการชำระเงิน', 'system');

  select pr.payment_code into v_payment_code
  from public.payment_requests pr
  where pr.entity_type = 'otop_order' and pr.entity_id = v_order.id
  limit 1;

  return query select v_order.id, v_order.order_code, v_order.subtotal_amount,
    v_order.shipping_fee, v_order.total_amount, v_payment_code, v_order.shipping_status;
end;
$$;

revoke all on function public.create_member_otop_order_v1(uuid,uuid,jsonb,uuid,text,text,text,text,numeric,text,text)
  from public, anon, authenticated;
grant execute on function public.create_member_otop_order_v1(uuid,uuid,jsonb,uuid,text,text,text,text,numeric,text,text)
  to service_role;

create or replace view public.ops_order_queue with (security_invoker=true) as
select o.id,o.order_code,o.status,o.fulfillment_type,o.total_amount,o.contact_status,
  o.source_channel,o.environment,o.customer_id,c.full_name_enc,c.email_enc,c.phone_enc,
  c.preferred_contact,c.is_test,c.test_label,o.customer_note,o.staff_note,o.created_at,o.updated_at,
  o.shipping_address_id,o.shipping_recipient_name_enc,o.shipping_phone_enc,o.shipping_address_enc,
  o.subtotal_amount,o.shipping_fee,o.shipping_status,o.carrier_name,o.tracking_number_enc,
  o.tracking_url,o.shipped_at,o.delivered_at
from public.otop_orders o
left join public.customer_accounts c on c.id=o.customer_id;

revoke all on public.ops_order_queue from public, anon, authenticated;
grant select on public.ops_order_queue to service_role;
